[workspace]
channels = ["conda-forge"]
name = "simgrad"
version = "0.1.0"
description = "Simplex gradient methods for optimization"
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.10.*"
numpy = ">=1.21.0"
pandas = ">=1.3.0"
scipy = ">=1.7.0"
matplotlib = ">=3.5.0"
tqdm = ">=4.62.0"
numba = ">=0.56.0"
jax = ">=0.4.0"
jaxlib = ">=0.4.0"
beautifulsoup4 = ">=4.10.0"
requests = ">=2.25.0"


